### ISSUE TITLE
How can I use xm4was to get  MXbeans for the hole cell from deploy manager ?

### ISSUE THREAD

**Issue by toni-moreno** [kszbcss/xm4was#12]
We are working in a OpenSource project to get health information from any websphere installation and send to a graphite backend.

Our main problem was accesing MXBeans as well as PMI data. But now it seem posible with your XM4WAS plugins.

The only doubt now is how to access MXBeans from any node/process  connecting only to the AdminClient  of the   Network deployment.

We would like queryNames like that:

* java.lang:process=server1,type=Memory

As well as we can do

* websphere:process=server1,type=XXX

How can we do that ?

**Comment by pvdbosch** [comment]
Hi, to make a MBean accessible through the AdminClient, you need to make sure you register the mbean on the right MBeanServer.

There are a couple of ways to retrieve the MBeanServer ([WebSphere doc](http://www-01.ibm.com/support/knowledgecenter/SSAW57_8.5.5/com.ibm.websphere.nd.multiplatform.doc/ae/tjmx_extend.html?lang=en)), I usually use the AdminServiceFactory class to retrieve it:

 MBeanFactory mbeanFactory = AdminServiceFactory.getMBeanFactory();
 MBeanServer mbeanServer = mbeanFactory.getMBeanServer();
